//! e2e: TLS-wrapped TCP transport.
//!
//! Starts a cqserver with a self-signed cert generated by the harness,
//! connects via the client SDK's TLS path with verification disabled
//! (tests only), and runs a publish → sow roundtrip — the same shape
//! the plain-TCP transport tests use. Proves the TLS handshake +
//! framing path is wired identically to plain TCP.

use cq_client::{tls_client_config_dangerous_no_verify, Client};
use cq_e2e_tests::{start_server_with, ServerOpts, TlsOpts, TopicSpec};
use serde_json::json;

#[tokio::test]
async fn tls_publish_and_sow_roundtrip() {
    let topic = TopicSpec::new("/tls-trades", "k")
        .with_inline_columns([("k", "string"), ("v", "double")]);

    let server = start_server_with(
        vec![topic],
        ServerOpts {
            outbound_queue_capacity: 1024,
            slow_consumer: None,
            tls: Some(TlsOpts::default()),
            queues: Vec::new(),
            auth: None,
            txlog_archive: None,
            views: Vec::new(),
            spillover: None,
            logging_sinks: Vec::new(),
            replication: None,
            hard_max_sow_result_rows: None,
            admin_token: None,
            admin_tls: None,
        },
    )
    .await;

    let tls_cfg = tls_client_config_dangerous_no_verify().expect("client tls config");
    let addr = format!("127.0.0.1:{}", server.tcp_port);
    let client = Client::connect_tls(&addr, "127.0.0.1", tls_cfg)
        .await
        .expect("tls connect");

    for i in 0..5 {
        client
            .publish(
                "/tls-trades",
                json!({ "k": format!("k{i}"), "v": i as f64 }),
            )
            .await
            .expect("publish over tls");
    }

    // SOW back over the same TLS connection.
    let rows = client
        .sow("/tls-trades", None)
        .await
        .expect("sow over tls");
    assert_eq!(rows.len(), 5, "expected 5 rows back from SOW, got {}", rows.len());

    let keys: Vec<&str> = rows
        .iter()
        .filter_map(|r| r.get("k").and_then(|v| v.as_str()))
        .collect();
    for i in 0..5 {
        let want = format!("k{i}");
        assert!(keys.contains(&want.as_str()), "missing key {want}: {keys:?}");
    }
}
