[package]
name = "cq-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
thiserror.workspace = true
compact_str.workspace = true
rmp-serde.workspace = true
bson.workspace = true
zstd.workspace = true
